# Generated by Django 6.0 on 2026-02-11 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mrn', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PATIENT', 'Patient')], default='DOCTOR', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('wound_location', models.CharField(blank=True, max_length=100, null=True)),
                ('wound_type', models.CharField(blank=True, max_length=100, null=True)),
                ('wound_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('depth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pain_level', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('granulation_pct', models.IntegerField(blank=True, null=True)),
                ('epithelial_pct', models.IntegerField(default=0)),
                ('slough_pct', models.IntegerField(default=0)),
                ('eschar_pct', models.IntegerField(default=0)),
                ('marker_data', models.TextField(blank=True, null=True)),
                ('doctor_suggestion', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.patient')),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(db_column='assessment_id', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.assessment')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.patient')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
